### ISSUE TITLE
Падает проект если обновится на yii-debug 2.0.11

### ISSUE THREAD

**Issue by asyou99** [ElisDN/yii2-demo-shop#20]
![image](https://user-images.githubusercontent.com/12735688/31318092-25a06616-ac55-11e7-8e2e-3faa66c89a07.png)
Вот такое сообщение выскакивает если обновится дебаг панель до последней версии на сейчас это 2.0.11

**Comment by asyou99** [comment]
Александр Макаров апнул дебаг до версии 2.0.12 и сказал что в ней данный баг пофиксили.

**Comment by ElisDN** [comment]
Да, пофиксили.
