### ISSUE TITLE
Product creation - other categories

### ISSUE THREAD

**Issue by Andrewkha** [ElisDN/yii2-demo-shop#21]
https://github.com/ElisDN/yii2-demo-shop/blob/9104d8cd254672769bc5d7e4711faaad3d760411/shop/useCases/manage/Shop/ProductManageService.php#L66

If other categories are empty, throws Invalid argument supplied for foreach() exception.
The same applies to Existing tags

**Comment by ElisDN** [comment]
Fixed.
