### ISSUE TITLE
If new tag was not provided, it will create a Tag with empty name

### ISSUE THREAD

**Issue by Andrewkha** [ElisDN/yii2-demo-shop#22]
https://github.com/ElisDN/yii2-demo-shop/blob/9104d8cd254672769bc5d7e4711faaad3d760411/shop/useCases/manage/Shop/ProductManageService.php#L86

**Comment by ElisDN** [comment]
Fixed.

**Comment by Andrewkha** [comment]
Sorry, can you please explain how it was fixed? I do not see any change in the ProductManageService code... Looks like it was done in some other place

**Comment by ElisDN** [comment]
I have added `['existing', 'default', 'value' => []]` validation rule instead of `beforeValidate()` method.

**Comment by Andrewkha** [comment]
If I understand correctly what you mean, it resolves another issue (if no existing tag is selected , the foreach loop fails). But what I'm talking about is if the New Tag is empty when you create/edit product, it will create a tag with empty name and slug and assign it to the product

![image](https://user-images.githubusercontent.com/9628186/33069279-127a7490-cec5-11e7-954a-40c60cd38a2b.png)
