### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by faenir** [ElisDN/yii2-demo-shop#24]
Где будет правильнее перевести поля бд в текущей архитектуре приложения? Сейчас `Yii::t()` не используется в коде. Если определить метод `attributeLabels()` в сущностях (`entities`), то их не видно, например, в формах (т.к. они не наследуются от сущностей). Делать в формах что-то вроде:
```php
public function attributeLabels()
{
    return $this->_category->attributeLabels();
}
```
тоже не очень как-то, да и не во всех формах есть доступ к сущности текущей. Дублировать тоже не хочется. Еще есть CompositeForm, MetaForm... Как?

**Comment by ElisDN** [comment]
Можно вообще отовсюду вынести в хелпер:

```php
public function attributeLabels()
{
    return UserHelper::attributeLabels();
}
```

**Comment by faenir** [comment]
Спасибо, хорошее решение, что-то не подумал об этом :)
