### ISSUE TITLE
backend -> Blog -> comments -> filter on active field

### ISSUE THREAD

**Issue by the-toxic** [ElisDN/yii2-demo-shop#25]
Filter not work.
/backend/forms/Blog/CommentSearch.php

Not correct:
`$query->andFilterWhere([
    'id' => $this->id,
    'post_id' => $this->post_id,
]);`

Need:
`$query->andFilterWhere([
    'id' => $this->id,
    'active' => $this->active,
]);`

**Comment by ElisDN** [comment]
Fixed. Thanks!
