### ISSUE TITLE
Должен быть slug

### ISSUE THREAD

**Issue by pamparam83** [ElisDN/yii2-demo-shop#26]
в блоге с id напутали,
мне кажется нужен slug для тегов

```
class TagReadRepository
{
    public function find($id): ?Tag
    {
        return Tag::findOne($id);
    }
}
```

**Comment by the-toxic** [comment]
Да да, тоже столкнулся недавно. Нужно искать по slug вместо id
`return Tag::findOne(['slug' => $slug]);`

**Comment by pamparam83** [comment]
было бы не плохо реализовать это что бы и так и так могло

**Comment by ElisDN** [comment]
Исправил.
