### ISSUE TITLE
[page & shop category] Исключение при попытке выбрать родительским элементом самого себя

### ISSUE THREAD

**Issue by the-toxic** [ElisDN/yii2-demo-shop#28]
До конца курса еще не дошел, но уже столкнулся с этой проблемой в 2х разделах, где реализован вложенный список через nested-set-behavior

_Страницы:_
/page/update?id=1
/shop/category/update?id=1

_Файлы:_
/backend/views/page/_form.php
/backend/views/shop/category/_form.php

Речь идет о селекте **parentId**

Решил исправить проблему повесив на option  атрибут disabled.
В методе dropDownList() есть опция, позволяющая это сделать нативно.

`<?= $form->field($model, 'parentId')->dropDownList(
                $model->parentsList(), ['options' => [Yii::$app->request->get('id') => ['disabled' => true]]]
            ) ?>`

Дмитрий, если есть более изящное решение - подскажите. Пока только изучаю фреймворк.

**Comment by hijackfl** [comment]
Описание огонь :)
При выборе родительской категории или страницы можно выбрать саму себя и естественно получаем exception.

ИМХО: так как удобно знать, где сейчас находится эта категория, то думаю можно делать так или передавать через params.

**Comment by ElisDN** [comment]
Тогда уж так:

```php
['options' => [$model->id => ['disabled' => true]]]
```

А вообще чтобы можно из parentsList() возвращать все элементы кроме своих дочерних по `lft < $model->lft OR rgt > $model->rgt`.
