### ISSUE TITLE
Type Exception

### ISSUE THREAD

**Issue by Andrewkha** [ElisDN/yii2-demo-shop#31]
https://github.com/ElisDN/yii2-demo-shop/blob/434c6a977445b3eb03e0404698998a1ef37117fa/shop/services/search/ProductIndexer.php#L50

Getting: Exception 'TypeError' with message 'Argument 1 passed to console\controllers\SearchController::console\controllers\{closure}() must be an instance of shop\entities\Shop\Category, instance of shop\entities\Shop\Product\CategoryAssignment given' for some reason... The code is exactly like in repo and in the Video, but...

**Comment by the-toxic** [comment]
Поддерживаю, тоже вчера столкнулся. Временно закомментировал этот кусок чтоб не ругалось
Очень странно, долго пытался понять как Category  может быть объектом класса CategoryAssignment, т.к. мы явно указываем ему обратное
`array_reduce(array_map(function (Category $category) {
    return ArrayHelper::getColumn($category->parents, 'id');
}, $product->categoryAssignments),'array_merge', [])`

**Comment by voidlz** [comment]
Вместо `$product->categoryAssignments`  должно быть `$product->categories` которая по связи hasMany через `categoryAssignments` и получает нужные нам данные.

**Comment by Andrewkha** [comment]
Попробую, во всяком случае, выглядит логично. Хотя при просмотре записи урока явно видно, что Дмитрий запускает код в консоли именно в таком виде

**Comment by ElisDN** [comment]
Fixed. Thanks!
