### ISSUE TITLE
Rest api urls & Swagger issues

### ISSUE THREAD

**Issue by voidlz** [ElisDN/yii2-demo-shop#34]
Не работают put, delete методы.

`consumes` должен быть `"application/x-www-form-urlencoded"`:
https://github.com/ElisDN/yii2-demo-shop/blob/d08247c609e5dba11230429d7d547afccee64093/api/controllers/SiteController.php#L13

`type` нужен `string`. мы hash принимает, а не integer
https://github.com/ElisDN/yii2-demo-shop/blob/d08247c609e5dba11230429d7d547afccee64093/api/controllers/shop/CartController.php#L146
https://github.com/ElisDN/yii2-demo-shop/blob/d08247c609e5dba11230429d7d547afccee64093/api/controllers/shop/CartController.php#L171

Ну и соответственно здесь тоже:
https://github.com/ElisDN/yii2-demo-shop/blob/d08247c609e5dba11230429d7d547afccee64093/api/config/main.php#L95-L96 

---
P.S. лень делать pull 😃

**Comment by ElisDN** [comment]
Спасибо! Исправил.
