### ISSUE TITLE
need to add use ($products) to the callback

### ISSUE THREAD

**Issue by Andrewkha** [ElisDN/yii2-demo-shop#35]
https://github.com/ElisDN/yii2-demo-shop/blob/d08247c609e5dba11230429d7d547afccee64093/shop/useCases/Shop/OrderService.php#L50

The $products array will be empty If use ($products) is not added to the callback => no products will be save in the transaction

**Comment by oleksanderzap** [comment]
you can do  `$items = array_map(function (CartItem $item) use (&$products) {...})`

**Comment by ElisDN** [comment]
Thanks! Fixed.
