### ISSUE TITLE
Не правильно установлена связь с табл. способов доставки.

### ISSUE THREAD

**Issue by the-toxic** [ElisDN/yii2-demo-shop#36]
Нужно ставить нулл  в "orders.delivery_method_id" при удалении способа доставки.
`$this->addForeignKey('{{%fk-shop_orders-delivery_method_id}}', '{{%shop_orders}}', 'delivery_method_id', '{{%shop_delivery_methods}}', 'id', 'SET NULL');`

**Comment by ElisDN** [comment]
Спасибо! Исправил.
