### ISSUE TITLE
Vagrant up

### ISSUE THREAD

**Issue by aram1991** [ElisDN/yii2-demo-shop#38]
при команде vagrant up появляется ошибка 
" There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
* The 'hostmanager' provisioner could not be found.

Vagrant:
* Unknown configuration section 'hostmanager'.
Установил плагин Vagrant Host Manager (через команду "vagrant plugin install vagrant-hostmanager"),проблема не решилься
В чем может быть проблема?

**Comment by the-toxic** [comment]
@aram1991
Если не ошибаюсь эта проблема появилась в какой-то из версий Parallels Desktop (если у вас мак), попробуйте обновить софтину до последней.

**Comment by aram1991** [comment]
Нет не Мас
OS - windows 10

**Comment by maxim-avramenko** [comment]
Коллеги, нынче Vagrant не модно, юзайте Docker, вот ссылка https://github.com/maxim-avramenko/shop
README.md ещё не обновил
Если будут вопросы - пишите

**Comment by savinAlexey** [comment]
В pach переменные среды добавить в значение путь до vagrant.exe, у меня он такой C:\HashiCorp\Vagrant\bin\vagrant.exe  Устанавливаем в директорию проекта vagrant plugin install vagrant-hostmanager
