### ISSUE TITLE
не подгружаются миграции

### ISSUE THREAD

**Issue by asder117** [ElisDN/yii2-demo-shop#47]
Вроде фремфорк обновлен но не подгружаются миграции. 
Yii Migration Tool (based on Yii v2.0.35)

Creating migration history table "migration"...Done.
PHP Warning 'yii\base\ErrorException' with message 'strncmp() expects parameter 1 to be string, array given'

in /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/BaseYii.php:133

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/BaseYii.php(133): strncmp()
#2 /var/www/html/yii2-demo-shop/vendor/fishvision/yii2-migrate/controllers/MigrateController.php(111): yii\BaseYii::getAlias()
#3 /var/www/html/yii2-demo-shop/vendor/fishvision/yii2-migrate/controllers/MigrateController.php(79): fishvision\migrate\contro              llers\MigrateController->getMigrationPaths()
#4 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(167): fishvision\migrate\cont              rollers\MigrateController->getNewMigrations()
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
#6 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#8 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#9 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#10 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#11 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#12 /var/www/html/yii2-demo-shop/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#13 /var/www/html/yii2-demo-shop/yii(27): yii\base\Application->run()

**Comment by ElisDN** [comment]
Проект написан три года назад. При обновлении до сегодняшней версии естественно будут ошибки.

**Comment by asder117** [comment]
Утро доброе Дмитрий..Спасибо за проект...ну я его под свои нужды пилю..сейчас вроде все взлетело. оно с путями косяки, пытаюсь понять где пути прописаны чтобы все отображалось и по ссылкам переходило..конфиги все излазил сижу перечитываю матчасть. а в миграциях простоя правки внес вроде все втянуло
